from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass


@dataclass(frozen=True)
class ChangedFile:
    status: str
    path: str


def run_git(args: list[str], check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", *args], check=check, text=True, capture_output=True)


def parse_status(porcelain: str) -> list[ChangedFile]:
    files: list[ChangedFile] = []
    for line in porcelain.splitlines():
        if not line:
            continue
        status = line[:2].strip() or line[:2]
        path = line[3:]
        if " -> " in path:
            path = path.split(" -> ", 1)[1]
        files.append(ChangedFile(status=status, path=path))
    return files


def generate_commit_message(files: list[ChangedFile]) -> str:
    paths = [changed.path for changed in files]
    if not paths:
        return "No changes"

    has_tests = any(path.startswith("tests/") for path in paths)
    has_docs = any(path.endswith(".md") or path.startswith(".devcontainer/") for path in paths)
    has_config = any(path.startswith("config/") or path in {"pyproject.toml", "Makefile", ".gitignore"} for path in paths)
    has_package = any(path.startswith("threaded_earth/") for path in paths)
    has_tools = any(path.startswith("tools/") for path in paths)

    if has_tools and len(paths) <= 4:
        subject = "Add automated checkpoint workflow"
    elif has_package and has_tests:
        subject = "Implement tested simulation slice"
    elif has_package:
        subject = "Update simulation package"
    elif has_tests:
        subject = "Add simulation tests"
    elif has_docs and has_config:
        subject = "Update project docs and configuration"
    elif has_docs:
        subject = "Update project documentation"
    else:
        subject = "Update project files"

    buckets = []
    if has_package:
        buckets.append("simulation code")
    if has_tests:
        buckets.append("tests")
    if has_tools:
        buckets.append("developer tooling")
    if has_config:
        buckets.append("configuration")
    if has_docs:
        buckets.append("documentation")

    body = f"Includes: {', '.join(buckets)}." if buckets else f"Touches {len(paths)} file(s)."
    return f"{subject}\n\n{body}\n\nGenerated by tools/checkpoint.py."


def current_branch() -> str:
    result = run_git(["rev-parse", "--abbrev-ref", "HEAD"])
    return result.stdout.strip()


def has_staged_changes() -> bool:
    result = run_git(["diff", "--cached", "--quiet"], check=False)
    return result.returncode != 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Stage changes, generate a commit message, commit, and optionally push.")
    parser.add_argument("--no-push", action="store_true", help="Commit locally but do not push.")
    parser.add_argument("--dry-run", action="store_true", help="Show the generated commit message without committing.")
    parser.add_argument("--message", help="Use an explicit commit message instead of generating one.")
    args = parser.parse_args()

    if not args.dry_run:
        run_git(["add", "-A"])
    status = run_git(["status", "--porcelain"]).stdout
    changed = parse_status(status)
    message = args.message or generate_commit_message(changed)

    if not changed:
        print("No source changes to commit.")
        return 0

    print("Generated commit message:")
    print(message)

    if args.dry_run:
        print("Dry run only; no commit created.")
        return 0

    if not has_staged_changes():
        print("No source changes to commit.")
        return 0

    run_git(["commit", "-m", message])
    if args.no_push:
        print("Committed locally; push skipped because --no-push was set.")
        return 0

    branch = current_branch()
    run_git(["push", "-u", "origin", branch])
    print(f"Committed and pushed to origin/{branch}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
